### ISSUE TITLE
mysql_user: Drop support for REQUIRESSL

### ISSUE THREAD

**Issue by Jorge-Rodriguez** [ansible-collections/ansible.mysql#101]
The `REQUIRESSL` privilege has been superseded by the more complete `tls_requires` option. The privilege has been kept for backwards compatibility, but in doing so it's introduced extra complexity in the module code and a number of idempotence issues.

With PR #97 we're planning a release with breaking changes. Here I'm proposing using the opportunity to drop the support for the `REQUIRESSL` privilege in the same breaking release.

**Comment by Andersson007** [comment]
I don't feel empowered to discuss the topic not being a MySQL user even (would be pretty dangerous to make any breaking decisions based on my suggestions, among other thing)
@bmalynovytch @bmildren @steveteahan what do you think?

**Comment by Andersson007** [comment]
I don't feel empoyered to discuss the topic not being a MySQL user even (would be pretty dangerous to make any breaking decisions based on my suggestions, among other thing)
@bmalynovytch @bmildren @steveteahan what do you think?

**Comment by bmalynovytch** [comment]
> With PR #97 we're planning a release with breaking changes. Here I'm proposing using the opportunity to drop the support for the `REQUIRESSL` privilege in the same breaking release.

I doubt most of sysadmins use REQUIRESSL with MySQL / MariaDB, even though it's recommended.
Most of the people impacted with this breaking change should be able to upgrade their configuration, along with the update of the module.

I'm fine with this approach.

**Comment by felixfontein** [comment]
Besides that it's nice to finally get rid of the "SSL" (and replace it with the correct "TLS"), since TLS is around for almost 22 years now (as successor to the SSL protocols) and the last SSL protocol (SSLv3) has been deprecated almost 6 years ago (after being broken, and not being recommended for many more years). :)
