### ISSUE TITLE
mysql_user: Mariadb new REPLICA MONITOR / SLAVE MONITOR privileges not supported

### ISSUE THREAD

**Issue by petracvv** [ansible-collections/ansible.mysql#105]
##### SUMMARY
Starting with MariaDB 10.5.9, the REPLICATION SLAVE ADMIN grant no longer allows SHOW SLAVE STATUS and SHOW RELAYLOG EVENTS as those are now covered by the SLAVE MONITOR grant (REPLICA MONITOR is an alias for SLAVE MONITOR).

See https://jira.mariadb.org/browse/MDEV-23610?focusedCommentId=173137&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-173137 for details in the upstream bug.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user module

##### ANSIBLE VERSION

Output below is a bit weird because this is in a VM with ansible in a virtualenv

```paste below
ansible 2.10.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ansible/lib64/python3.6/site-packages/ansible
  executable location = /tmp/ansible/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
DEFAULT_FORCE_HANDLERS(/etc/ansible/ansible.cfg) = True
DIFF_ALWAYS(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

This is on RHEL8 with MariaDB 10.5.9 installed from their upstream repository

##### STEPS TO REPRODUCE

Try to create a user with the SLAVE MONITOR privilege and the module exits with an error about a wrong privilege.

```yaml
- name: Create test user
   community.mysql.mysql_user:
     name: nagios
     host: localhost
     password: 'testpassword'
     priv: '*.*:SELECT,SLAVE MONITOR
```

##### EXPECTED RESULTS

The module will grant the slave monitor privilege

##### ACTUAL RESULTS

The module exits with the error: invalid privileges string: Invalid privileges specified: frozenset({'SLAVE MONITOR'})"

```paste below
failed: [localhost] (item={'user': 'nagios', 'priv': '*.*:PROCESS,SLAVE MONITOR,SELECT', 'resource': {'MAX_USER_CONNECTIONS': 10}}) => {"ansible_loop_var": "item", "changed": false, "item": {"priv": "*.*:PROCESS,SLAVE MONITOR,SELECT", "resource": {"MAX_USER_CONNECTIONS": 10}, "user": "nagios"}, "msg": "invalid privileges string: Invalid privileges specified: frozenset({'SLAVE MONITOR'})"}
```

**Comment by Andersson007** [comment]
@petracvv hi, thanks for reporting this! I created a PR https://github.com/ansible-collections/community.mysql/pull/108

**Comment by Andersson007** [comment]
@petracvv merged, thank you

**Comment by petracvv** [comment]
Thanks for the work on this!
