### ISSUE TITLE
mysql_user follow up on column privileges

### ISSUE THREAD

**Issue by ghost** [ansible-collections/ansible.mysql#106]
##### SUMMARY

Issue #99  got partially solved by PR #100. It would be great to generalize this solution to work with all column privileges. The MySQL 8.0 documentation (https://dev.mysql.com/doc/refman/8.0/en/grant.html#grant-column-privileges) specifies the following column privileges:

 INSERT, REFERENCES, SELECT, and UPDATE

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user

**Comment by Andersson007** [comment]
@JaSafieddine thanks for the issue! I'm working on it

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.mysql/pull/107 the final tests passed. I made a small adjustment in tests. They should pass again, so ready for review

**Comment by Andersson007** [comment]
fyi: there are false codecov failings. the units and integration passed

**Comment by Andersson007** [comment]
@JaSafieddine thanks for reporting!
@Jorge-Rodriguez thanks for reviewing!

I've just release community.mysql 1.3.0, so the changes will appear in Ansible 3.1.0 tomorrow, hope we didn't introduce new bugs:D
Despite the CI tests, if you can try it soon, I'd be grateful for feedback
Thanks everyone!
