### ISSUE TITLE
mysql_user: Analyze a possibility to remove privs frozenset at all

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#110]
##### SUMMARY
There were a lot of reports that mysql_privs does not support valid privileges. For example https://github.com/ansible-collections/community.mysql/pull/108
I think it's very annoying for users.
We should analyze removing the VALID_PRIVS frozenset where we usually just add such privs to.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mysql_user

**Comment by Andersson007** [comment]
After investigation: no, we can't just remove the frozenset and get rid of the check safely without huge refactoring.
Reason: there are several cursor with autocommit like 1) create a user 2) grant privileges.
If there's an invalid priv passed, the user will be created (and will stay in the database) but the module will fail on the grand privs step. So it will lead to inconsistency.

The option is to subscribe on MySQL and MariaDB release notes and other mailing list which allow us to know about new options better some time before they are released.

@bmalynovytch @Jorge-Rodriguez @rndmh3ro if anyone subscribed on such lists, would be great if we update the VALID_PRIVS frozenset in advance or give me links where i can subscribe and I will track in myself. I think it's very serious problem when users can't use recently-introduce privileges

**Comment by rndmh3ro** [comment]
I only know of the public changelogs:
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/
https://mariadb.com/docs/release-notes/

Subscribing to these could be enough since distributions also take some time to release these new version.

**Comment by Andersson007** [comment]
@rndmh3ro thanks! I have an accound, logged in, but don't see any buttons like "Subscribe" or something

**Comment by Andersson007** [comment]
Seems i found it, it's in profile settings

**Comment by Andersson007** [comment]
i think it's there https://www.mysql.com/news-and-events/newsletter/

**Comment by Andersson007** [comment]
Who's interesting, please subscribe too. We could make the collection users much happier acting proactively (and i think it's good to be informed in general)

**Comment by Andersson007** [comment]
mariadb announce newsletter subscription (i think they should publish new thing there) is https://lists.askmonty.org/cgi-bin/mailman/listinfo/announce

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.mysql/pull/217
