### ISSUE TITLE
mysql_user: get full mysql version string as a variable

### ISSUE THREAD

**Issue by rndmh3ro** [ansible-collections/ansible.mysql#114]
##### SUMMARY
Right now if you use `mysql_info` to get the version of the database, you get back a dict with three items for the major, minor and release version. However it's hard to use this variable in a version-comparison (e.g. `when:  mysql_version is version('5.6', '>=')`), because you first have to construct a new variable from the dict.

Therefore I propose to add a new variable (e.g. `full_mysql_version`) that contains the full version string.

One open question for me: would this be a new filter or should this new variable be returned in the `version`-filter?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mysql_info

##### ADDITIONAL INFORMATION

Sample code:

```
    def __get_global_variables(self):
        """Get global variables (instance settings)."""
        res = self.__exec_sql('SHOW GLOBAL VARIABLES')

        if res:
            for var in res:
                self.info['settings'][var['Variable_name']] = self.__convert(var['Value'])

            ver = self.info['settings']['version'].split('.')
            release = ver[2].split('-')[0]

            self.info['version'] = dict(
                major=int(ver[0]),
                minor=int(ver[1]),
                release=int(release),
            )

+            self.info['full_version']  = self.info['settings']['version']
```

**Comment by Andersson007** [comment]
@rndmh3ro hi, thanks for the issue!
I like the idea, sounds sensible!
I suggest naming it maybe like `raw_mysq_version`?
Would you like to implement it yourself or i could?

**Comment by Andersson007** [comment]
oh, sorry, "full_version" is OK!

**Comment by Andersson007** [comment]
> One open question for me: would this be a new filter or should this new variable be returned in the version-filter?

@rndmh3ro I think we could add this to `version`, e.g.:
```
            self.info['version'] = dict(
                major=int(ver[0]),
                minor=int(ver[1]),
                release=int(release),
                full_version='...',
            )
```

**Comment by rndmh3ro** [comment]
I'll try to implement it.
~I'll use as a new filter `full_version` and return `raw_mysql_version`? Or should have both the filter and the variable the same name?~

I like that as you suggested:

```
            self.info['version'] = dict(
                major=int(ver[0]),
                minor=int(ver[1]),
                release=int(release),
                full_version='...',
            )```

**Comment by Andersson007** [comment]
@rndmh3ro cool, thanks!
And i don't remember (i have no instance of mysql right now) whether it always contains `mariadb` / `mysql` in it? I think it does.
If yes, we could put a key with it to the dict as well but i'm not sure how to name it.

**Comment by Andersson007** [comment]
(@rndmh3ro don't forget to add a check to tests/integration/targets/test_mysql_info)

**Comment by Andersson007** [comment]
(and feel free to add yourself to `authors:`)

**Comment by Andersson007** [comment]
So, i think we should also put in the dict a key, say called `type:`, containing `mariadb` or `mysql` (i.e. what is before `-` in a version string)

**Comment by rndmh3ro** [comment]
> So, i think we should also put in the dict a key, say called type:, containing mariadb or mysql (i.e. what is before - in a version string)

I'll add that, however it's not always `mariadb` or `mysql`. Maybe call the variable simply `suffix`?
```
        
MariaDB [(none)]> select version();
+----------------+
| version()      |
+----------------+
| 5.5.68-MariaDB |


mysql> select version();
+-------------------------+
| version()               |
+-------------------------+
| 5.7.33-0ubuntu0.18.04.1 |
+-------------------------+
```

**Comment by Andersson007** [comment]
@rndmh3ro ah, thanks, i mixed up the format with postgresql. Yeah, `suffix` sounds good to me, I'm sure it can be useful
