### ISSUE TITLE
MySQL community pinboard

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#12]
_Copied from https://github.com/ansible/community/issues/439_

We could collectively benefit from forming a Working Group related to MySQL and MariaDB integration. We have quite some contributors and users that are interested in improving this integration.

So this issue is a call to potential interested parties (earlier and existing contributors to Ansible). The benefits of having a [Working Group](https://github.com/ansible-collections/community.mysql/wiki/MySQL-Working-Group) is that members of the Working Group can:

- test, review and add shipits to existing MySQL PRs
- work collectively on a MySQL roadmap
- provide a single-point-of-contact for interested MySQL contributors
- collaborate on a MySQL-specific Wiki

**Comment by Andersson007** [comment]
cc @bmalynovytch @bmildren @Jorge-Rodriguez @Alexander198961 @tolland @Xyon

**Comment by Andersson007** [comment]
@Jorge-Rodriguez feel free to add yourself to the table there https://github.com/ansible-collections/community.mysql/wiki/MySQL-Working-Group

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 I don't seem to be able to edit the wiki to add myself to the table.

**Comment by Andersson007** [comment]
@Jorge-Rodriguez ah, sorry, just changed settings, could you please try again

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 alright, I managed now.
On a different matter, do you mind if I place the [chilicorn](https://spiceprogram.org/chilicorn/) logo on the repo readme?

**Comment by Andersson007** [comment]
@Jorge-Rodriguez i personally don't mind if it's free to use:) @bmildren @bmalynovytch ?

**Comment by Jorge-Rodriguez** [comment]
For clarification, chilicorn is a program run by my parent company. So they are subsidizing the work I've been doing here.

**Comment by bmildren** [comment]
It's just my personal opinion and I hate to be a grinch, but admirable as it is imho we shouldn't add individual programs / sponsorships to a community repo.  It places undue focus on an individual organisation / contributor, and it could get pretty crowded if all members of the working group (current and future), placed sponsorships from their organisations, it would also lead to an awkward clean up when contributions go stale.

**Comment by Andersson007** [comment]
in terms of sponsorship, ads, etc., @bmildren 's thoughts sound sensible to me

**Comment by Jorge-Rodriguez** [comment]
👍 agreed. I'm closing the PR

**Comment by Andersson007** [comment]
Hi folks, if bugfix PRs authors don't seem to be going to complete their stuff (e.g. to add changelog fragments or CI tests or whatever), i suggest completing such things ourselves not waiting the good whether from the see, say, 1-2 weeks of no feedback. Depends on a bug, of course - potential blockers should be fixed ASAP.

@Jorge-Rodriguez , if no feedback in 2-3 days https://github.com/ansible-collections/community.mysql/pull/41, feel free to fix

**Comment by Andersson007** [comment]
@Jorge-Rodriguez 
1) do you need that 2 branches https://github.com/ansible-collections/community.mysql/branches ?
2) have you seen my email? (nothing urgent or super important)

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 I don't need the branches, thank you for reminding me that they were left over, I've deleted then now. And yes, I saw your email. I've been meaning to answer but things have been quite busy on my end.

**Comment by Andersson007** [comment]
@Jorge-Rodriguez cool, thanks for the confirmation! There's even no need to answer. It was just random thoughts:) I wanted to be sure it didn't end up in a spam folder or something.

**Comment by Andersson007** [comment]
FYI: I'm releasing `community.mysql 2.0.0` tomorrow morning (2021-04-15)

**Comment by Andersson007** [comment]
FYI: In addition to fully replace `stopslave`, `startslave`, etc. state values with corresponding `stopreplica`, etc. in `community.mysql 3.0.0` next autumn, I've just announced replacement of `Is_Slave` with `Is_Replica` (I'll add a warning ASAP).

W're also gonna replace `master` with `primary`.

**Comment by Andersson007** [comment]
This is the plan for 3.0.0:
```
major_changes:
- mysql_replication - the return value ``Is_Slave`` and ``Is_Master`` will be replaced with ``Is_Replica`` and ``Is_Primary`` in ``community.mysql`` 3.0.0 (https://github.com/ansible-collections/community.mysql/issues/145).
- mysql_replication - the word ``master`` in messages returned by the module will be replaced with ``primary`` in ``community.mysql`` 3.0.0 (https://github.com/ansible-collections/community.mysql/issues/145).
```
+ dropping support for REQUIRESSL (see https://github.com/ansible-collections/community.mysql/pull/132)

**Comment by Andersson007** [comment]
community.mysql 2.0.0 has been released

New branch stable-2 has been created as well

It means that we have to backport to `stable-2` (by cherry-picking from `main`) all changes we'll merge to `main` since now (except breaking changes!).
I created a label `needs_backport_to_stable-2` - please put it on all PRs you'll merge since now, then create backports. Thanks!
Don't put this label on PRs with breaking changes! :)

I'll try to nail down `ansibullbot` here later to create backports automatically.

**Comment by Andersson007** [comment]
I'm happy to announce that the registration (free) for the Ansible Contributor Summit is open.

Which day should you attend?

- If you are wondering what it means to "contribute" to Ansible, or if you have been using Ansible for a while and are thinking of ways to get more involved with the project and community, then Day 1 (September 28, Tuesday) is for you!
- If you have already been contributing or participating in our previous Contributor Summits, you are still welcome to attend Day 1, however we think that Day 2 (October 1, Friday) will be more interesting for you.

Refer to the [registration page](https://ansiblecs202109.eventbrite.com/?aff=github) for details.

See you at the summit!

**Comment by dericcrago** [comment]
[AnsibleFest]: https://www.ansible.com/ansiblefest
[Ansible Contributor Summit]: https://ansiblecs202109.eventbrite.com/?aff=github
[Hackathon]: https://hackmd.io/@ansible-community/contrib-summit-202109#Hackathon
[Ansible Contributor Summit 2021.09 HackMD]: https://hackmd.io/@ansible-community/contrib-summit-202109

**Reminder - [AnsibleFest] and [Ansible Contributor Summit] are 1 week away!**

In case you missed it, we will also be having a **[Hackathon]** throughout the entire **[Ansible Contributor Summit]** and **[AnsibleFest]**. This is a great opportunity to collaborate in real time with other members of the Ansible Community!

For more info and the latest updates, please see the **[Ansible Contributor Summit 2021.09 HackMD]**.

**Comment by Andersson007** [comment]
[Ansible Contributor Summit]: https://ansiblecs202109.eventbrite.com/?aff=github
[Hackathon]: https://hackmd.io/@ansible-community/contrib-summit-202109#Hackathon
[Ansible Contributor Summit 2021.09 HackMD]: https://hackmd.io/@ansible-community/contrib-summit-202109

**Reminder** - Day 1 of the [Ansible Contributor Summit] and the [Hackathon] start tomorrow (Tuesday, 28 September 2021)!

For more info and the latest updates, please see the **[Ansible Contributor Summit 2021.09 HackMD]**.

**Comment by Andersson007** [comment]
[Ansible Contributor Summit]: https://ansiblecs202109.eventbrite.com/?aff=github
[Hackathon]: https://hackmd.io/@ansible-community/contrib-summit-202109#Hackathon
[Ansible Contributor Summit 2021.09 HackMD]: https://hackmd.io/@ansible-community/contrib-summit-202109

**Reminder** - Day 2 of the [Ansible Contributor Summit] and the last day of the [Hackathon] start tomorrow (Friday, 1 October 2021)!

For more info and the latest updates, please see the **[Ansible Contributor Summit 2021.09 HackMD]**.

**Comment by Andersson007** [comment]
FYI: if someone else from current maintainers wants to release 3.1.1 and 2.3.4 (in other words learn how to release / become a release engineer here), I would be happy to lead you through the process. Please let me know:)

p.s. we can wait for the day / time suitable for you

**Comment by laurent-indermuehle** [comment]
FYI: I'm releasing community.mysql 1.4.8, 2.3.9  and 3.4.0

**Comment by laurent-indermuehle** [comment]
The community.mysql collection versions [1.4.8](https://github.com/ansible-collections/community.mysql/blob/stable-1/CHANGELOG.rst), [2.3.9](https://github.com/ansible-collections/community.mysql/blob/stable-2/CHANGELOG.rst) and [3.4.0](https://github.com/ansible-collections/community.mysql/blob/main/CHANGELOG.rst) have been released.

**Comment by laurent-indermuehle** [comment]
The community.mysql collection version [3.8.0](https://github.com/ansible-collections/community.mysql/releases/tag/3.8.0) has been released.

**Comment by Andersson007** [comment]
Moving to forum, closing this one. Please join the [group](https://github.com/ansible-collections/community.mysql/pull/589) and let's continue on the forum, thanks everyone!
