### ISSUE TITLE
mysql_replication: replace Is_Slave and Is_Master returned value with Is_Replica and Is_Primary in community.mysql 3.0.0, replace master in messages with primary

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#145]
##### SUMMARY
mysql_replication: replace `Is_Slave` and `Is_Master` return value with `Is_Replica` and `Is_Primary` in `community.mysql 3.0.0`
mysql_replication: replace the word `master` in messages with `primary`

Announced in https://github.com/ansible-collections/community.mysql/pull/144

1. Add alternatives for `master*` state values similarly to https://github.com/ansible-collections/community.mysql/pull/97

2. Add alternative ret values for `Is_Slave` and `Is_Master` - done in https://github.com/ansible-collections/community.mysql/pull/147

2. Add "Warning" when state is `getreplica` / `getslave` and `getmaster` / `getprimary` - done in https://github.com/ansible-collections/community.mysql/pull/147

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.mysql/pull/147

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.mysql/pull/252

**Comment by nerijus** [comment]
Now it does not work with mariadb versions <10.5, for example, 10.4.
If I use `slave_pos`:
```
value of primary_use_gtid must be one of: current_pos, replica_pos, disabled, got: slave_pos
```
If I use `replica_pos`:
```
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'replica_pos' at line 1")
```
