### ISSUE TITLE
Update the list of supported connectors (especially the links) in README.

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#167]
##### SUMMARY
Update the list of supported connectors (especially the links) in README.

I think it's incorrect as it is now:
```
 23 The MySQL modules rely on a MySQL connector. The list of supported drivers is below:
 24 
 25 - [PyMySQL](https://github.com/PyMySQL/PyMySQL)
 26 - [MySQLdb](https://github.com/PyMySQL/mysqlclient-python)
 27 - Support for other Python MySQL connectors may be added in a future release.
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
README.md

**Comment by Andersson007** [comment]
would be grateful for any help with it

**Comment by ziegenberg** [comment]
**MySQLdb**
As CentOS 7 has an EOL of mid-2024 and currently brings MySQL-python in version 1.2.5, RHEL 8 brings version 1.4.6, Ubuntu 18.04 LTS (EOL mid-2023) brings version 1.3.10 and Ubuntu 20.04 LTS (EOL mid-2025) brings 1.4.4.
So 1.2.5 seems like a sensible lower bound.

**PyMySQL**
RHEL 8 brings version 0.8.0, CentOS 7 provides 0.9.3 via EPEL and Ubuntu 18.04 LTS (EOL mid-2023) brings also version 0.8.0 and and Ubuntu 20.04 LTS (EOL mid-2025) brings 0.9.3. Same goes for Debian 10.
So 0.8.0 might be a good lower bound.

**Comment by Andersson007** [comment]
@ziegenberg thanks for the info! @Jorge-Rodriguez ^ FYI.

The question also is that we have the `mysqlclient` and `PyMySQL` repos under `https://github.com/PyMySQL/` organization.
As we can see in the current README, the MySQLdb link points to https://github.com/PyMySQL/mysqlclient. Is that correct?
1. Same question said in other words: is MySQLdb == mysqlclient or it is different entities? From this question, the other ones raise:
2. Are the links correct?
3. Should we add mysqlclient if it's another entity?
4. How should we arrange them? I mean if, say, mysqlclient is better developed than the other two, should we put in on the top of the list?

If somebody knows the answers, feel free to raise a quick PR.

**Comment by ziegenberg** [comment]
**PyMySQL**
If you enable the python38 module from AppStreams on RHEL 8 / CentOS 8, you get Version 0.9.3 instead of 0.8.0 (which should also bring compatibility with `caching_sha2_password`).

**Comment by ziegenberg** [comment]
As far as I understand it: 'MySQLdb == mysqlclient' is correct. mysqlclient is a fork of MySQLdb1and both `mysqlclient` and `PyMySQL` reside under the `https://github.com/PyMySQL/` organization.

Which is better? How should we arrange them?
That's a more difficult question. Both seem to be under active development.

PyMySQL is a pure Python MySQL Client and has no dependencies outside of Python.
mysqlclient on the other hand relies on certain MySQL libs to be present. That can be a challenge, e.g. when you use Percona on RHEL8. Installing Percona XtraDB Cluster disables the MySQL package module. Now you can't install `python3-mysqlclient` from your repo any longer, as it depends on mysql-libs, which is provided by the disabled MySQL package module. Using PyMySQL is one possible solution.

**Comment by Andersson007** [comment]
@ziegenberg thanks for the detailed explanation!
Now it's clear that if we install mysqlclient, `import MySQLdb` will work.

@ziegenberg @Jorge-Rodriguez does it make sense to split the line `- [MySQLdb](https://github.com/PyMySQL/mysqlclient-python)` into something like:
```
...
- [mysqlclient](https://github.com/PyMySQL/mysqlclient-python)
- [MySQLdb](https://github.com/farcepest/MySQLdb1)
```
?
or maybe changing `MySQLdb` -> `mysqlclient` in the current sentence?

If README is relevant now and fine in this part, that's good. If someone knows how it can be improved / clarified, feel free to create a quick PR. E.g., in addition, we could put the nuances mentioned in the comments in README a bit below of the list or just `(recommended)` to PyMySQL (if we want).

**Comment by Jorge-Rodriguez** [comment]
@ziegenberg thank you so much for the info.
@Andersson007 I need some time to digest all this information and figure out how it fits in our CI plans, I'll come back to this with clearer ideas (hopefully).

**Comment by rsicart** [comment]
Hi,

does this PR https://github.com/ansible-collections/community.mysql/pull/250 fix this issue?

**Comment by Andersson007** [comment]
@rsicart @Jorge-Rodriguez @ziegenberg thank you! (if there are any objections on the implementation https://github.com/ansible-collections/community.mysql/pull/250, we'll reopen the issue)

**Comment by Andersson007** [comment]
Should we update the `requirements` section in https://github.com/ansible-collections/community.mysql/blob/main/plugins/doc_fragments/mysql.py adding `mysqlclient`?
If anyone is happy to do it, please go ahead. If no time, let me know.
