### ISSUE TITLE
mysql_user support of REQUIRE NONE to remove granted REQUIRE-SSL

### ISSUE THREAD

**Issue by drzraf** [ansible-collections/ansible.mysql#20]
##### SUMMARY
There is no way to remove the "REQUIRE SSL" mysql privilege ... other than rewriting the whole set of permission which is not practicable (especially when depending upon `append_privs=yes`)

Eg: After setting `REQUIRESSL`
`-  mysql_user: name=muser priv="*.*:REQUIRESSL" append_privs=yes`

... there is no way to revert such a directive. Normally this is done using REQUIRE NONE
But this is not implemented by the Ansible role.

`-  mysql_user: name=muser priv="*.*:REQUIRENONE" append_privs=yes`

Expected result: The REQUIRE SSL is droped for _muser_

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mysql_user

##### ADDITIONAL INFORMATION
https://github.com/ansible/ansible/issues/15440
https://github.com/ansible/ansible/issues/29811

**Comment by Andersson007** [comment]
cc @Jorge-Rodriguez

**Comment by Jorge-Rodriguez** [comment]
This should be handled by setting the `tls_requires` parameter to an empty dictionary.
Requires should not be used to handle TLS connection requirements

**Comment by Andersson007** [comment]
@Jorge-Rodriguez 1) shouldn't we cover the case by CI tests and 2) add an example to EXAMPLE block?
If you want (I think it would be great because you're the feature's author, so you know better), feel free to make a PR. If not, I could.

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 I'll have to look at the code, but I vaguely remember that we have both of those things.
But if it turns out that I'm wrong about this, I'll be more than happy to add it.
