### ISSUE TITLE
Being able to set a replication filter on database 

### ISSUE THREAD

**Issue by bmillemathias** [ansible-collections/ansible.mysql#214]
##### SUMMARY
I'm looking for the possibility to set a replication filter on database to only replicate transaction for those databases.
In MySQL, this is equivalent to `CHANGE REPLICATION FILTER REPLICATE_DO_DB=(db1,db2);` 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
mysql_replication

##### ADDITIONAL INFORMATION
The feature would permit to define a replication but limited to a define scope of databases
`CHANGE REPLICATION` can have other filters as mentioned on https://dev.mysql.com/doc/refman/5.7/en/change-replication-filter.html

**Comment by Andersson007** [comment]
@bmillemathias thanks for reporting the feature idea!

**Comment by rsicart** [comment]
Hi @bmillemathias 

does this PR https://github.com/ansible-collections/community.mysql/pull/266 fix your issue?

**Comment by Andersson007** [comment]
@bmillemathias could you please try the new argument https://github.com/ansible-collections/community.mysql/pull/266 and let us know if it helps (if it doesn't, we'll reopen the issue).
@bmillemathias @rsicart thank you!
