### ISSUE TITLE
Add testing against MariaDB to CI, add more MySQL versions (at least the latest at the moment)

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#224]
##### SUMMARY
Add testing against MariaDB to CI and the latest MySQL version. Currently we test with MySQL 5.7.31 and 8.0.22

Related files (maybe something else):
```
.github/workflows/ansible-test-plugins.yml
tests/integration/targets
```

**Comment by rsicart** [comment]
Hey @Andersson007 ,

Does PR https://github.com/ansible-collections/community.mysql/pull/246 fix this issue?

**Comment by Andersson007** [comment]
@rsicart thanks for purging irrelevant issues!
