### ISSUE TITLE
Documentation: Add note to README how to run CI tests locally

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#27]
##### SUMMARY
Documentation: Add a note to README how to run CI tests locally.

Now it fails when not default container is specified. We must run it just with `--docker` cli argument without passing any distribution name

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
README.md

**Comment by Andersson007** [comment]
@bmildren please take a look https://github.com/ansible-collections/community.mysql/wiki/Testing-your-changes and fix if you find anything wrong or add anything you consider important

**Comment by Andersson007** [comment]
@Jorge-Rodriguez ^

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 In my experience, none of the **Prepare Testing Environment** steps are needed, except for the installation of docker. But it is necessary to place the collection repository in a path where `ansible-test` expects it.
Let me try this on a fresh environment to verify.

**Comment by Andersson007** [comment]
@Jorge-Rodriguez thanks for looking at that!
The steps can be needed to use the dev version of `ansible-test`, I stumbled upon that once, it can be important but, on the other hand, it was a couple of months ago, maybe it's not so relevant after the stuff with collections got stable.
Anyway, i'd use dev version of ansible-test. I'll make a note.

Ok, will be waiting your feedback, feel free to fix the page on the spot.

**Comment by Andersson007** [comment]
added some changes to https://github.com/ansible-collections/community.mysql/wiki/Testing-your-changes

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.mysql/wiki/Testing-your-changes
