### ISSUE TITLE
mysqlclient doesn't work with mariadb

### ISSUE THREAD

**Issue by rsicart** [ansible-collections/ansible.mysql#292]
##### SUMMARY

Integration tests do not pass for roles and they have been disabled in #291 . 
See https://github.com/ansible-collections/community.mysql/pull/291/checks?sha=1ebcfb1a77eadc3dbd47a0157b8002229b0c2dfe for more details.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Integration tests for roles

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by Andersson007** [comment]
@rsicart thanks for creating the issue!

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.mysql/pull/293
