### ISSUE TITLE
Can't grant multiple privileges for the same db.table combination

### ISSUE THREAD

**Issue by davelukes-pp** [ansible-collections/ansible.mysql#294]
##### SUMMARY

Apologies if this is a duplicate, but I've searched the issues list and I can't see anything like this.

If you have something like:
```
  priv:     '*.*:SELECT/*.*:SHOW VIEW'
```
in a `mysql_user` task, the user will be granted the `SHOW VIEW` privilege and not the `SELECT` privilege.
I've tested several different combinations and if you have the same `db.table` combination this will always happen.

My _limited_ knowledge of python suggests that this is the problem:
https://github.com/ansible-collections/community.mysql/blob/82cedf85108af7238d4e5bb7a0229424d7490893/plugins/module_utils/user.py#L581
because the loop over the list of privileges overwrites the previous privilege with the current privilege instead of concatenating them.

If I get some spare time (ha!) I'll try to put together a PR to fix this, but given the limits on my time and python skills it will take a while,
so if someone else wants to fix it in the meantime that would be great 🙂.

Thanks. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user
##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dave.lukes/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]

```
... but the ansible version is irrelevant.

##### COLLECTION VERSION

```paste below
sorry, my ansible-galaxy is too old to support list
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

See above

```yaml
  priv:     '*.*:SELECT/*.*:SHOW VIEW'
```

##### EXPECTED RESULTS

Multiple privileges granted.

##### ACTUAL RESULTS

Only the last privilege granted.

```paste below
N/A
```

**Comment by Andersson007** [comment]
@davelukes-pp hi, thanks for the issue and your interest in helping with this collection! We always need more hands and eyes!

I would suggest:
1. trying to pass multiple privs using commas, i.e. `priv: '*.*:SELECT,SHOW VIEW'`? Could you please try on your and the latest version? We have it in our CI and it seems to work. If it works, feel free raise a PR to update the EXAMPLES block in the module's file (i.e. add one more example)
2. trying the latest version of this collection. You could [install ansible-core](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-core) on your test machine and the [latest version of the collection](https://github.com/ansible-collections/community.mysql#using-this-collection).
3. we have the [Quick start guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) which helps newcomers to start quickly 

Thank you!

**Comment by davelukes-pp** [comment]
Hi @Andersson007,
Thanks.

1. Yes, I know that I can pass multiple privs using commas and that works,
but in my use case I'm merging multiple sets of privs from separate sources, so this would be much more difficult.
AFAICS this is a bug, or at least an undocumented "feature", so it should at least be documented if not fixed.
1. The latest version of the collection still has the same bug in it: I know because I've read the code.
1. Thanks for the [Quick start guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) link.
I will submit a PR when I have the time, if no-one else has fixed it already.

**Comment by Andersson007** [comment]
@davelukes-pp yes, i see now. Not sure if we should change it or just document. I would prefer documenting because the case feels generally a bit rarer.
@rsicart @bmalynovytch @Jorge-Rodriguez any thoughts?

**Comment by rsicart** [comment]
I would say that the fastest and less intrusive is documenting.

**Comment by Andersson007** [comment]
@davelukes-pp would you like to submit a doc PR?

**Comment by davelukes-pp** [comment]
Thanks @Andersson007.
🤔
At the moment, the doc says nothing, which _implies_ that it should work, so submitting a doc PR also changes the implied behaviour ...

Because I am the only person affected by this (so far!), it seems to me that fixing the code would be better because it will not affect anyone else and it will fix my problem (and anyone else's problem if they try this in the future).

So, I would prefer to submit a code PR as soon as I am happy that it will fix the problem.
Would you mind if I work it up into a code PR?  I'll need to create some test cases first.

It is a 1 line fix, something like:
```
dbpriv[i] = dbpriv[i] + ('' if dbpriv[i] == '' else ',') + '%s%s%s' % (quote, side.strip('`'), quote)
```

**Comment by Andersson007** [comment]
@davelukes-pp 
>At the moment, the doc says nothing, which implies that it should work, so submitting a doc PR also changes the implied behaviour ...

I would disagree as it would, imo, just confirm the actual behavior:)

>Because I am the only person affected by this (so far!), it seems to me that fixing the code would be better because it will not affect anyone else and it will fix my problem (and anyone else's problem if they try this in the future).

You know, my experience is telling me that changing the code can often make unexpected side effects..:) And it would be especially undesirable in such an important part of such the important module.
So that's why we prefer changing documentation in similar cases. I wouldn't say this is a bug because i personally wouldn't expect in your case the module should necessarily concatenate privileges. Another person can expect that the current (overwriting) behavior is correct.. hard to say.
So for me +1 to reflecting the current behavior in the doc. As I can see @rsicart as a maintainer is also in favor of doc changes. 

@bmalynovytch, our WG leader, and @Jorge-Rodriguez , your thoughts, folks?

**Comment by davelukes-pp** [comment]
@Andersson007 
Of course I defer to you and the rest of the maintainers,
but I must say that I think that there is an important issue here:
the current behaviour _**silently** ignores_ some of the given privileges. How can this be correct?
Either it should use all the privileges or it should warn that it is ignoring the previous privileges.
I can't think of any situation where you would want to supply 2 sets of privileges and only have one set used.
Why would you ever want that behaviour?

I understand about the unexpected side effects problem, but that's why you have comprehensive test suites, right?

As I said: I defer to you as the experts, so please go ahead with the doc change if you think that's the right thing to do.

**Comment by Andersson007** [comment]
@davelukes-pp thanks for reporting the issue and reviewing the PR!
@rsicart thanks for reviewing!
