### ISSUE TITLE
Support the session variable wsrep_on = off for the Galera cluster

### ISSUE THREAD

**Issue by janggwan-im** [ansible-collections/ansible.mysql#478]
##### SUMMARY

The session variable `wsrep_on = off` is useful to update db users without affecting other Galera cluster nodes.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

mysql.user

##### ADDITIONAL INFORMATION

https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-on

```yaml

```

**Comment by Andersson007** [comment]
@janggwan-im hello, thanks for reporting the issue request!
In case someone is interested in picking it up, there's a [quick start dev](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) guide that can help

**Comment by Andersson007** [comment]
@janggwan-im is it a system variable? Can we use https://docs.ansible.com/ansible/latest/collections/community/mysql/mysql_variables_module.html to set it up?

**Comment by janggwan-im** [comment]
It is also a system variable, but what I want is to use it as session variable.

**Comment by Andersson007** [comment]
> It is also a system variable, but what I want is to use it as session variable.

aha, thanks for the context, in this case, it should be something general like, say, another argument called maybe `session_vars`, so the interface could look like:
```
community.mysql.mysql_user:
  ...
  session_vars:
    wsrep_on: off
```
those vars will be executed by the module before doing the main work

@janggwan-im @laurent-indermuehle @betanummeric @rsicart ideas on ^ ?

**Comment by Andersson007** [comment]
i see the support for the interface, does anyone want to pick it up?
in case you're new here, here's the [Quick-start dev guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) available for you

**Comment by Andersson007** [comment]
I'm working on it

**Comment by Andersson007** [comment]
Merged.
@janggwan-im thanks for reporting the feature request!
