### ISSUE TITLE
CI: add testing against stable-2.15 to CI matrix

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#528]
##### SUMMARY
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/41

- Add corresponding lines to https://github.com/ansible-collections/community.mysql/tree/main/.github/workflows
- Maybe new sanity errors will appear. It's usually straightforward to fix though.

**Comment by laurent-indermuehle** [comment]
I close this, was fixed in #574

**Comment by Andersson007** [comment]
@laurent-indermuehle great, thanks a lot for the contribution!
