### ISSUE TITLE
Executing an sql script file

### ISSUE THREAD

**Issue by Zverik** [ansible-collections/ansible.mysql#54]
##### SUMMARY

I would like a module that takes an sql file (either local or remote, but can also be just remote) and does `mysql < file.sql`.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

mysql_execute, or an option for mysql_query

##### ADDITIONAL INFORMATION

Sometimes an application does not have its installer that initializes a database, but requires to run some SQL file that creates tables and populates them.

See for example [postgresql_query](https://docs.ansible.com/ansible/latest/collections/community/general/postgresql_query_module.html) module that can receive a `path_to_script` argument.

**Comment by Andersson007** [comment]
@Zverik hi, thanks for the issue!
@bmalynovytch as far as i remember we discussed this when developing the module. Didn't you change your mind about adding `path_to_script` option:)?

**Comment by Zverik** [comment]
I've noticed `mysql_db` has this feature (using `state: import` and `target: /path/to/script.sql`), but it isn't obvious. Sometime one would want to run e.g. maintenance scripts.

**Comment by Andersson007** [comment]
@Zverik one issue which will probably appear is the anybody once will try to restore a dump via `path_to_script` and will report about bugs;) That happened to `postgresql_query`. Yes, we can add a note about this as did with `postgresql_query` but anyway. I'd like to here more opinions.
We could:
1. add `path_to_script` or
2. add a note to `mysql_query`'s description about possibility to run scripts via `mysql_db` to make it more obvious. @Zverik how about this?

**Comment by Zverik** [comment]
So yeah, I've read these issues, and I see there might be some ambiguity. I'd choose 2 since that's less work, and most of the scripts worth running create tables anyway :)

**Comment by Andersson007** [comment]
@Zverik , agreed, https://github.com/ansible-collections/community.mysql/pull/55

**Comment by Zverik** [comment]
Thanks!
