### ISSUE TITLE
Galaxy: check and fix galaxy collection links

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#576]
##### SUMMARY
In order to implement https://github.com/ansible-collections/news-for-maintainers/issues/59, we should check and fix all Galaxy collection urls if they present in the repo

**Comment by laurent-indermuehle** [comment]
@Andersson007 I searched for "galaxy" in the whole repo. Didn't find any link in main.

**Comment by Andersson007** [comment]
@laurent-indermuehle thanks a lot for checking! Closing then
