### ISSUE TITLE
GHA: add testing against stable-2.17

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#622]
##### SUMMARY
As stable-2.17 of ansible-core has been recently [branched](https://forum.ansible.com/t/ansible-core-devel-bumped-to-2-18-0-dev0-stable-2-17-branch-created/4695/1) (so now devel is 2.18), we need to explicitly add testing against `stable-2.17` to our GHA CI matrix

**Comment by Andersson007** [comment]
@laurent-indermuehle when you're back from PTO, could you please take a look?

**Comment by laurent-indermuehle** [comment]
@Andersson007 I'm back! Sure.
I'll drop support for 2.14 at the same time.
Not sure if 2.15 should also be removed: https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html

**Comment by Andersson007** [comment]
@laurent-indermuehle cool, thanks!
I think 2.15 will be still [supported](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) until November, so I would keep it there as it's a requirement for included collections to support all supported core versions.
