### ISSUE TITLE
When using Ansible's mysql_query module ，result is that 'admin' is being censored

### ISSUE THREAD

**Issue by yasyx** [ansible-collections/ansible.mysql#637]
When using Ansible's mysql_query module to execute the SQL query:

SELECT TABLE_NAME FROM information_schema.TABLES where TABLE_NAME='op_admin_log'
And the result is that 'admin' is being censored, turning into 'op_******_log'。

![image](https://github.com/ansible-collections/community.mysql/assets/12021357/2c5691cb-cd79-4ecd-af63-3936410af6c6)

**Comment by yasyx** [comment]
because mysql password is `admin`

**Comment by Andersson007** [comment]
@yasyx hello, thanks for opening the issue! This ansible behavior isn't always good but it's how `ansible-core` handles these things for security reasons and we have no levers in this collection to make it not do this. Anyway, thanks!
