### ISSUE TITLE
Mention MariaDB in documentation

### ISSUE THREAD

**Issue by robertsilen** [ansible-collections/ansible.mysql#639]
##### SUMMARY
Ansible supports MariaDB with the mysql community module (as I understand). However MariaDB is not mentioned in the documentation for [Community.Mysql — Ansible Community Documentation](https://docs.ansible.com/ansible/latest/collections/community/mysql/index.html) and it's modules. In practice many users are running MariaDB, so it should be mentioned more explicitly in each individual mysql module’s documentation - at least under Synopsis and Notes. I can make a suggestion with a Pull Request after comments. 

I was suggested to open this issue after [asking about this in the Ansible forum](https://forum.ansible.com/t/mention-mariadb-in-documentation/6030). 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Possible files to edit
* line 28: [community.mysql/changelogs/config.yaml at main · ansible-collections/community.mysql · GitHub](https://github.com/ansible-collections/community.mysql/blob/main/changelogs/config.yaml#L28)
* line 8: [community.mysql/galaxy.yml at main · ansible-collections/community.mysql · GitHub](https://github.com/ansible-collections/community.mysql/blob/main/galaxy.yml#L8)
* line 1: [community.mysql/README.md at main · ansible-collections/community.mysql · GitHub](https://github.com/ansible-collections/community.mysql/blob/main/README.md?plain=1#L1)

What others do you suggest? 

##### ANSIBLE VERSION
Latest published versions of documentation. 

I also found [Database modules — Ansible Documentation](https://docs.ansible.com/ansible/2.9/modules/list_of_database_modules.html#mysql) , but apparently does not exist since 2.9

**Comment by Andersson007** [comment]
@robertsilen hello, it's a great suggestion! Would you like to submit a PR? if you have no experience, it's as simple as in the [quick start guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) with skipping all test related steps. What do you think?

**Comment by robertsilen** [comment]
Thanks! I made a Pull Request that adds MariaDB in README.md, galaxy.yml, changelogs/config.yaml and seven module py-files' descriptions and notes. See https://github.com/ansible-collections/community.mysql/pull/640 Hope that is meeting expectations?

**Comment by Andersson007** [comment]
Closed via https://github.com/ansible-collections/community.mysql/pull/640 , thanks!
