### ISSUE TITLE
mysql_variables always changes on boolean values

### ISSUE THREAD

**Issue by rafi0101** [ansible-collections/ansible.mysql#652]
##### SUMMARY
in MariaDB mysql_variables always mark boolean variables as changed if I use 0 oder 1 as value.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.mysql.mysql_variables

##### ANSIBLE VERSION
```paste below
ansible [core 2.16.8]
```

##### COLLECTION VERSION
```paste below
community.mysql 3.9.0
```

##### CONFIGURATION
/

##### OS / ENVIRONMENT
/

##### STEPS TO REPRODUCE
try to change any boolean variable with this module in MariaDB and set the value to 0 or 1 in ansible.
"ON" or "OFF" is working. (btw without quotation marks it is also not working, because ansible then translate it to True or Falso which is not a valid MariaDB value)

I know what the Problem is:
MariaDB accept at leaset 0,1,ON and OFF for booleans but always converts the value to ON or OFF. Now the module always wants to change the value from OFF to 0 which is the same. So especially for boolean values the "when is a variable changed" should be adjusted.

and no, changing all values from 0 to OFF in ansible would be too easy for me :D

##### EXPECTED RESULTS
should not show changed if the value is 0/OFF or 1/ON

##### ACTUAL RESULTS
```paste below
    "msg": "Variable change succeeded prev_value=OFF",
    "queries": [
        "SET GLOBAL `log_slow_slave_statements` = 0"
    ]
```

**Comment by Andersson007** [comment]
@rafi0101 hello, thanks for the issue report! Looking

**Comment by Andersson007** [comment]
@rafi0101 https://github.com/ansible-collections/community.mysql/pull/653 has been merged, thanks for the contribution!
