### ISSUE TITLE
When is a new release planned?

### ISSUE THREAD

**Issue by andygrunwald** [ansible-collections/ansible.mysql#666]
I would like to know when a new release is planned?

I see that since v3.9.0 a few useful changes have been implemented: https://github.com/ansible-collections/community.mysql/compare/3.9.0...main

I am personally interested in Add salt parameter to hash generation for sha256 plugins (https://github.com/ansible-collections/community.mysql/pull/631) at https://github.com/ansible-collections/community.mysql/commit/0bc3e3d848f8e3714ec2e6a7748ab1b85660e216

Is there a plan from your side already?
Anything how I can support in this?

**Comment by Andersson007** [comment]
@andygrunwald hello, thanks for asking and offering help! We were tackling some issues, that's why it got delayed.
@laurent-indermuehle is there anything we're waiting for before releasing the collection?

**Comment by laurent-indermuehle** [comment]
@Andersson007 Hi! Long time! Aren't we waiting on #651 before release of 3.10?

**Comment by Andersson007** [comment]
@laurent-indermuehle he has time/technical  issues to implement it. I think the module is generally insecure, so i think we can release. What do you think?

**Comment by laurent-indermuehle** [comment]
@Andersson007 you're right, the module is insecure for a long time. This shouldn't block a new release.

**Comment by Andersson007** [comment]
Done, https://galaxy.ansible.com/ui/repo/published/community/mysql/
@andygrunwald check out the [README](https://github.com/ansible-collections/community.mysql#installing-the-collection-from-ansible-galaxy) to learn how to update the collection locally. Make sure you report any bugs you spotted:)

@andygrunwald @laurent-indermuehle thanks! Closing as resolved
