### ISSUE TITLE
mysql_db import/dump always use default port, regardless of config file

### ISSUE THREAD

**Issue by JoelFeiner** [ansible-collections/ansible.mysql#68]
##### SUMMARY
If MySQL is running on a port other than 3306, even if you have the alternate port in `~/.my.cnf`, it is still required to provide `login_port` to `mysql_db` when dumping/importing or it can't connect.

It looks like the problem is here: https://github.com/ansible-collections/community.mysql/blob/main/plugins/modules/mysql_db.py#L468

It always adds the port to the command line and unless I set the port explicitly, it'll always be the default 3306. My recommendation is that tt shouldn't do that unless the host/port are explicitly set or there is no config file.

I tested `mysqldump` without a `--port` option and using just my local config file (which includes the port). It was able to dump successfully. So I don't think the port is required.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_db

##### ANSIBLE VERSION

```paste below
ansible 2.7.18
  config file = /<redacted>/ansible.cfg
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/ansible/lib/python3.7/site-packages/ansible
  executable location = /usr/local/ansible/bin/ansible
  python version = 3.7.9 (default, Aug 18 2020, 02:07:21) [GCC 9.3.0]
```

##### OS / ENVIRONMENT

Local OS: Ubuntu 20.04 and also CentOS 7.7
Target OS: CentOS 7.7

##### STEPS TO REPRODUCE

```yaml
- name: "Apply template to empty database"
  mysql_db:
    db: 'somedb'
    # the following is required for this to work, even though port is already specified in /root/my.cnf
    login_port: 13306
    target: '/tmp/database_template.sql'
    state: import
  become: true
```

##### EXPECTED RESULTS

Database is imported without the `login_port` variable.

##### ACTUAL RESULTS

The module is unable to connect to MySQL since it is using the wrong port.

```paste below
fatal: [dbhost.example.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "collation": "",
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "db": "somedatabase",
            "encoding": "",
            "ignore_tables": [],
            "login_host": "localhost",
            "login_password": null,
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": null,
            "name": "somedatabase",
            "quick": true,
            "single_transaction": false,
            "ssl_ca": null,
            "ssl_cert": null,
            "ssl_key": null,
            "state": "import",
            "target": "/tmp/database_template.sql"
        }
    }
}

MSG:

ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (111)
```

**Comment by Andersson007** [comment]
@JoelFeiner hi, thanks for reporting this!
`ansible 2.7.18` is out of support
could you please:
1) first try to run this with Ansible **2.10**
2) if the same, please run the playbook with `-vvv` and put the output starting from traceback (including it) and all below

Thanks!

**Comment by Andersson007** [comment]
closed because no feedback
@JoelFeiner if something changes, please let me know, thanks!
