### ISSUE TITLE
append_privs attempts to change privileges when it doesn't need to

### ISSUE THREAD

**Issue by steveteahan** [ansible-collections/ansible.mysql#69]
##### SUMMARY
append_privs usage will result in detecting a change to permissions even when the set of current privileges is a superset of new privileges.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION

```
ansible 2.10.3
  config file = None
  configured module search path = ['/home/$USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/$USER/.local/share/virtualenvs/ansible-testing-3MbEpyMU/lib/python3.8/site-packages/ansible
  executable location = /home/$USER/.local/share/virtualenvs/ansible-testing-3MbEpyMU/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION
```
no output (isolated test environment)
```

##### OS / ENVIRONMENT
This doesn't seem to be specific to the environment in any way.

##### STEPS TO REPRODUCE
1. `docker run -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=password -d mysql:5.7`
2. `create database test; use test; create table users (id int primary key);`
3. `ansible-playbook mysql.yml`
4. Run the command above for a second time and confirm that the plugin doesn't detect any changes
5. Remove the INSERT privileges from the play and run the playbook again.  The plugin detects that a change was made.  Continue to run this any number of times and a change will always be detected.

```yaml
---

- name: Test MySQL
  gather_facts: false
  hosts: localhost
  tasks:

    - name: Create database user with privileges
      mysql_user:
        login_user: root
        login_password: password
        login_host: 127.0.0.1
        name: bob
        password: '12345'
        host: '%'
        priv: 'test.users:SELECT,INSERT'
        append_privs: true
        state: present
```

##### EXPECTED RESULTS
The expected behavior is that the current privileges (SELECT,INSERT) should not require a change if the new permissions are SELECT.

##### ACTUAL RESULTS
The play will always report a change because the current permissions (MySQL grant tables) and new permissions (defined in Ansible play) will never match.

I am not ruling out that this could be the desired behavior.  What isn't clear to me is whether the purpose of `append_privs` is to avoid the REVOKE statement (which can result in outage), or whether it is to indicate that the only concern is that the current privileges are a superset of the new privileges.  The current behavior is not truly reporting whether change is happening to the user or not.  Additionally, it's running grants that could be skipped.

A simple implementation that would fix this particular issue (requires more testing) is:

```python
                # If appending privileges, only the permissions that exist in the new privileges, but not the current
                # privileges matter (difference vs. symmetric difference).
                if append_privs:
                    priv_diff = set(new_priv[db_table]) - set(curr_priv[db_table])
                else:
                    priv_diff = set(new_priv[db_table]) ^ set(curr_priv[db_table])
```

Some examples of expected behavior using this code:

```
current: SELECT
new: SELECT,INSERT
result: change

current: SELECT,INSERT
new: DELETE
result: change

current: SELECT,INSERT
new: SELECT
result: unchanged
```

This change would definitely require more testing for edge cases that I've missed.  I'm happy to run with this because there might be some additional changes that I'd like to contribute in the near future.

If the current behavior is the desired behavior, it might be helpful to change the documentation on append_privs to include:

* intent of this parameter (to avoid the potential for outage vs. ensuring current privileges are at least as permissive as new permissions)
* note that a change will always be detected if the permissions do not match exactly

Thank you for the work on this plugin!

**Comment by Andersson007** [comment]
@steveteahan thanks for reporting the issue!
@Jmainguy @bmalynovytch @tomaszkiewicz dear authors could you please specify what is the desired behavior?
Waiting for your feedback. Thanks!

**Comment by Andersson007** [comment]
cc @Alexander198961 @michaelcoburn @oneiroi @tolland @Xyon @kurtdavis

**Comment by steveteahan** [comment]
I went ahead and created a PR that will hopefully further clarify the behavior that I was expecting.  The new test was failing before my change (as expected) and I verified that the integration/sanity tests are now passing with my proposed change.

**Comment by Andersson007** [comment]
left a note there, thanks

**Comment by Andersson007** [comment]
@steveteahan thanks for fixing this again!

I've just released community.mysql 1.1.2 containing the fix which tarbal is available [here](https://galaxy.ansible.com/community/mysql) to download and use. The changes will also appear in the next Ansible package patch release. How to install in manually, refer to [this document](https://docs.ansible.com/ansible/devel/user_guide/collections_using.html)

Would be perfect if you start watching this repository. If anything related to your changes appears, you'll know about it.
