### ISSUE TITLE
SHOW_ROUTINE privilage is not in frozenset

### ISSUE THREAD

**Issue by skoriy88** [ansible-collections/ansible.mysql#86]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```ansible 2.9.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Sep 30 2020, 13:38:04) [GCC 7.5.0]
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

##### STEPS TO REPRODUCE

Try to add SHOW_ROUTINE privilege to MySQL user

```
- name: AWS RDS user
  community.mysql.mysql_user:
    append_privs: true
    state:          present
    name:           "my-user"
    host:           '%'
    priv:
      '*.*:USAGE/*.*:FILE/*.*:SHOW_ROUTINE'
    login_host:     '{{ rds.connection.host     }}'
    login_port:     '{{ rds.connection.port     }}'
    login_user:     '{{ rds.connection.user     }}'
    login_password: '{{ rds.connection.password }}'
```

##### EXPECTED RESULTS

Append SHOW_ROUTINE (https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_show-routine) privilege to user 

##### ACTUAL RESULTS

"msg": "invalid privileges string: Invalid privileges specified: frozenset(['SHOW_ROUTINE'])"

```
```

**Comment by Andersson007** [comment]
@skoriy88 thanks for reporting this! https://github.com/ansible-collections/community.mysql/pull/87

**Comment by Andersson007** [comment]
@skoriy88 i'll merge the PR, thanks. I'll put a comment here when i release the next version of the collection

**Comment by Andersson007** [comment]
FYI: `community.mysql` collection 1.2.0 has just been released.
The tarbal is available on [Galaxy](https://galaxy.ansible.com/community/mysql).
How to install it, see the [official guide](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html).
The changes will also be included in the next Ansible release.
