### ISSUE TITLE
mysql_replication: change the word SLAVE to REPLICA in messages returned by the module in the next major release

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.mysql#98]
##### SUMMARY
mysql_replication: change the word SLAVE to REPLICA in messages returned by the module in the next major release

Currently it's `community.mysql` of version 1.2.0

The announcement has been made in https://github.com/ansible-collections/community.mysql/pull/97

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_replication

**Comment by Jorge-Rodriguez** [comment]
As we continue the work to remove offensive language, we should also change instances of "MASTER" to "PRIMARY" instead.

**Comment by Andersson007** [comment]
Sounds good!

**Comment by Andersson007** [comment]
@Jorge-Rodriguez if you want to do it yourself, please put something here before starting or I could take a look tomorrow or next week.

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.mysql/pull/252
